name: webapp
services:
  demo:
    environment:
      - CATALINA_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"
    build: .
    depends_on:
      - mysql
    ports:
      - 8080:8080
      - 8000:8000

  mysql:
    image: mysql
    ports:
     - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: budget

